name: Deploy website

on:
  push:
    branches:
      - main   # usa master se necessario !

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout codice
        uses: actions/checkout@v4

      - name: Verifica secrets
        run: |
          if [ -z "${{ secrets.FTP_SERVER }}" ]; then echo "FTP_SERVER vuoto!"; else echo "FTP_SERVER OK"; fi
          if [ -z "${{ secrets.FTP_USERNAME }}" ]; then echo "FTP_USERNAME vuoto!"; else echo "FTP_USERNAME OK"; fi
          if [ -z "${{ secrets.FTP_PASSWORD }}" ]; then echo "FTP_PASSWORD vuoto!"; else echo "FTP_PASSWORD OK"; fi

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
